# Generated by Django 5.2.8 on 2026-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university_id', models.BigIntegerField(unique=True)),
                ('national_id', models.BigIntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('image', models.ImageField(upload_to='students/')),
            ],
        ),
    ]
