# Generated by Django 5.2.8 on 2025-12-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('university_id', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
